version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
  
  server:
    build:
      context: ./services/server
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
    depends_on:
      - db

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
      args:
        ROOT_API: /api
    ports:
      - 8080:8080
    depends_on:
      - db
      - server

  nginx:
    image: nginx:1.13
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - server
      - client

volumes:
  database_data:
    driver: local