apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.ingress.name }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.service.name }}
          servicePort: {{ .Values.service.port }}
